#:kivy 1.0

<Controller>:
    label_wid: my_custom_label

    BoxLayout:
        orientation: 'vertical'
        padding: 10
        
        BoxLayout:
            orientation: 'horizontal'
            padding: 5
                
            Label:
                id: my_custom_label
                text: 'Drink'
                font_size: '24sp'
                
        BoxLayout:
            orientation: 'horizontal'
            padding: 5
                
            